/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/usergupide/tutorial_java_projects.html
*/

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    jcenter()
    maven {
        url = uri("https://maven.scijava.org/content/groups/public")
    }

    if (project.hasProperty("useMavenLocal"))
        mavenLocal()
}

dependencies {
    // Paintera
    implementation("org.janelia.saalfeldlab:paintera:${project.version}")
}

application {
    // Define the main class for the application.
    mainClassName = "org.janelia.saalfeldlab.paintera.Paintera"
}
