#!/bin/sh

groupId="org.janelia.saalfeldlab"
artifactId="paintera"
version="${VERSION:-0.1.0-SNAPSHOT}"
mainClass="org.janelia.saalfeldlab.paintera.Paintera"

jrun \
    ${JAVA_OPTS} \
    "${groupId}:${artifactId}:${version}:${mainClass}" \
    $@
