#!/bin/sh
# postinst script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

package_type=deb
LAUNCHER_AS_SERVICE_SCRIPTS

case "$1" in
    configure)
DESKTOP_COMMANDS_INSTALL
ln -s /opt/paintera/bin/paintera /usr/local/bin/paintera
LAUNCHER_AS_SERVICE_COMMANDS_INSTALL
if [ -f /opt/paintera/lib/app/paintera.svg ]; then
    install -Dm644 /opt/paintera/lib/app/paintera.svg /usr/share/icons/hicolor/scalable/apps/paintera.svg
    command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
